export const table01Columns = [
    'Nº UNIDADE',
    'FILIAL',
    'CONTRATO',
    'PROPRIETÁRIO',
    'DATA FINAL NEGOCIAÇÃO',
    'STATUS NEGOCIAÇÃO',
    'TIPO DE NEGOCIAÇÃO',
    'VALOR ANTIGO',
    'DESCONTO %',
    'VALOR DESCONTO',
    'VALOR NOVO',
    'PRAZO',
    'SAVING DESCONTO',
    'ISENÇÃO',
    'SAVING REAJUSTE',
    'SAVING TOTAL GERAL',
    'NEGOCIAÇÃO',
    'ÍNDICE DE REAJUSTE',
    'MÊS BASE',
    'ANO',
    'ÍNDICE REAL',
    'CUSTO EVITADO',
    'INICIO DA VIGÊNCIA',
    'FIM DA VIGÊNCIA',
    'VERIFICADOR ISENÇÃO',
    'LIMITADOR SAVING PRAZO DE DESCONTO',
    'R$ BASE SAVING DESCONTO',
    'LIMITADOR SAVING % DESCONTO',
    'R$ FEE DESCONTO',
    'LIMITADOR SAVING PRAZO DE ISENÇÃO',
    'R$ BASE SAVING ISENÇÃO',
    'R$ FEE ISENÇÃO',
    'R$ FEE TOTAL'
]

export const table01MockData = [
    10652,
    '04 0140 - FOZI - PR',
    45,
    'PEVI ADMINISTRAÇÃO DE IMÓVEIS LTDA., PEVI ADMINISTRAÇÃO DE IMÓVEIS LTDA.',
    '01/11/2023',
    'Negociação Concluída',
    'REDUÇÃO',
    52947.64,
    5.57,
    2947.64,
    50000.00,
    84,
    247601.76,
    0,
    0,
    247601.76,
    null,
    null,
    null,
    null,
    null,
    null,
    '01/01/2024',
    '20/12/2030',
    'SIM',
    36,
    106115.04,
    5.57,
    5907.53,
    0,
    0,
    0,
    5907.53
];
